// Writes src/economy/city-record.ts, CITY's settled record (R*), which a town spawns from. It takes about 2.4 s: run it in
// any commit that changes CITY or the economy day, and commit the result. --check compares instead, as test:headless does.
import { readFileSync, writeFileSync } from 'node:fs';
import { CITY } from '../src/economy/city.ts';
import { settledRecord } from '../src/economy/settled.ts';
import { TIER_AGENTS, TIER_FIRMS, type Tier } from '../src/memory/tiers.ts';
import { firmsFitTier } from '../src/spawn/record.ts';

const FILE = new URL('../src/economy/city-record.ts', import.meta.url);
const NAME = 'packages/sim-core/src/economy/city-record.ts';
const HEADER = '// Generated by scripts/city-record.ts. Do not edit.';

function moduleSource(record: Float64Array): string {
  return `${HEADER}\nexport const CITY_RECORD = /* @__PURE__ */ new Float64Array([${record.join(', ')}]);\n`;
}

// A town of a tier's whole crowd takes firms at the record's ratio, and createTown throws when they pass the tier's rows.
function requireFirmsFitTiers(record: Float64Array): void {
  for (const tier of Object.keys(TIER_AGENTS) as Tier[]) {
    if (!firmsFitTier(record, tier)) {
      throw new RangeError(
        `CITY's record would put more than ${TIER_FIRMS[tier]} firms in a ${tier} town of ${TIER_AGENTS[tier]}`,
      );
    }
  }
}

const record = settledRecord(CITY);
requireFirmsFitTiers(record);
const text = moduleSource(record);
if (!process.argv.includes('--check')) {
  writeFileSync(FILE, text);
  console.log(`wrote ${NAME}`);
} else if (readFileSync(FILE, 'utf8').replace(/\r\n/g, '\n') === text) {
  console.log(`${NAME} matches a fresh settledRecord(CITY)`);
} else {
  console.error(`${NAME} is out of date: run node packages/sim-core/scripts/city-record.ts and commit the result`);
  process.exitCode = 1;
}
