// Writes src/economy/city-record.ts, CITY's settled record (R*), which a town spawns from. It takes about 2.4 s: run it in
// any commit that changes CITY or the economy day, and commit the result. --check compares instead, as test:headless does.
import { readFileSync, writeFileSync } from 'node:fs';
import { CITY } from '../src/economy/city.ts';
import { settledRecord } from '../src/economy/settled.ts';

const FILE = new URL('../src/economy/city-record.ts', import.meta.url);
const NAME = 'packages/sim-core/src/economy/city-record.ts';
const HEADER = '// Generated by scripts/city-record.ts. Do not edit.';

function moduleSource(record: Float64Array): string {
  return `${HEADER}\nexport const CITY_RECORD = /* @__PURE__ */ new Float64Array([${record.join(', ')}]);\n`;
}

const text = moduleSource(settledRecord(CITY));
if (!process.argv.includes('--check')) {
  writeFileSync(FILE, text);
  console.log(`wrote ${NAME}`);
} else if (readFileSync(FILE, 'utf8').replace(/\r\n/g, '\n') === text) {
  console.log(`${NAME} matches a fresh settledRecord(CITY)`);
} else {
  console.error(`${NAME} is out of date: run node packages/sim-core/scripts/city-record.ts and commit the result`);
  process.exitCode = 1;
}
