import { writeFileSync } from 'node:fs';

// src/time/calendar.ts imports the file this script writes, so the script cannot import calendar.ts.
const DAYS_PER_YEAR = 112;
const MIDSUMMER_DAY = 42;
const NOON_MINUTE = 720;
const MEAN_LIGHT_MINUTES = 720;
const LIGHT_SWING_MINUTES = 120;
const VALUES_PER_ROW = 7;
const HEADER = '// Generated by scripts/day-length.ts. Do not edit. Minutes after midnight, one entry per day of the year.';

export function dayLengthTable(): { sunrise: number[]; sunset: number[] } {
  const sunrise: number[] = [];
  const sunset: number[] = [];
  for (let day = 0; day < DAYS_PER_YEAR; day++) {
    const phase = (2 * Math.PI * (day - MIDSUMMER_DAY)) / DAYS_PER_YEAR;
    const halfLightMinutes = Math.round((MEAN_LIGHT_MINUTES + LIGHT_SWING_MINUTES * Math.cos(phase)) / 2);
    sunrise.push(NOON_MINUTE - halfLightMinutes);
    sunset.push(NOON_MINUTE + halfLightMinutes);
  }
  return { sunrise, sunset };
}

function declaration(name: string, minutes: number[]): string {
  const rows: string[] = [];
  for (let first = 0; first < minutes.length; first += VALUES_PER_ROW) {
    rows.push(`  ${minutes.slice(first, first + VALUES_PER_ROW).join(', ')},`);
  }
  return `export const ${name} = new Uint16Array([\n${rows.join('\n')}\n]);`;
}

function moduleSource(): string {
  const { sunrise, sunset } = dayLengthTable();
  return `${HEADER}\n${declaration('SUNRISE', sunrise)}\n${declaration('SUNSET', sunset)}\n`;
}

if (import.meta.main) {
  writeFileSync(new URL('../src/time/day-length.ts', import.meta.url), moduleSource());
}
