import { writeFileSync } from 'node:fs';
import exp from '@stdlib/math-base-special-exp';
import log2 from '@stdlib/math-base-special-log2';
import pow from '@stdlib/math-base-special-pow';
import sin from '@stdlib/math-base-special-sin';
import cdf from '@stdlib/stats-base-dists-normal-cdf';
import quantile from '@stdlib/stats-base-dists-normal-quantile';
import { apportion, createApportionScratch } from '../src/maths/apportion.ts';
import { DAYS_PER_YEAR } from '../src/time/calendar.ts';
import { reserveArena } from '../src/memory/arena.ts';
import { SUBPIXELS } from '../src/world/space.ts';

const Q15 = 32768;
const Q16 = 65536;
const Q30 = 1_073_741_824;
const MAX_UINT16 = 65535;
const TWO_POW_32 = 4294967296;
const PPM = 1_000_000;
const SCRATCH_ARENA_BYTES = 65_536;
const MANTISSA_ENTRIES = 256;
const EXP2_SEGMENTS = 64;
const INV_NORMAL_ENTRIES = 4096;
const BAND_CUTS = [4.0, 5.5, 7.0, 8.5];
const BAND_COUNT = BAND_CUTS.length + 1;
const BAND_SD = 1.9;
const BAND_ROWS = 201;
const BAND_MEANS_PER_POINT = 20;
const COPULA_SIDE = 64;
const COPULA_SPEARMAN = 0.6;
const HEADINGS = 256;
const QUARTER_TURN = HEADINGS / 4;
const WALK_Q8_PER_TICK = 4 * SUBPIXELS;
const WEIGHT_ENTRIES = 256;
const MAX_WEIGHT = (1 << 12) - 1;
const VALUES_PER_ROW = 16;
const HEADER = '// Generated by scripts/tables.ts. Do not edit.';

// Math.round rounds half up, toward +Infinity, as the tables promise.
function log2Table(): number[] {
  const table: number[] = [];
  for (let m = 0; m < MANTISSA_ENTRIES; m++) table.push(Math.round(Q16 * log2(1 + m / MANTISSA_ENTRIES)));
  return table;
}

// 2^(k / 64) in Q30 for k = 0 to 64. The last entry is 2^31, one past Int32Array.
function exp2Table(): number[] {
  const table: number[] = [];
  for (let k = 0; k <= EXP2_SEGMENTS; k++) table.push(Math.round(Q30 * pow(2, k / EXP2_SEGMENTS)));
  return table;
}

// Runs from day 0 to the first day that rounds to 0.
function fadeTable(halfLifeYears: number): number[] {
  const halfLifeDays = halfLifeYears * DAYS_PER_YEAR;
  const table: number[] = [];
  let value: number;
  do {
    value = Math.round(Q15 * pow(2, -table.length / halfLifeDays));
    table.push(value);
  } while (value > 0);
  return table;
}

function inverseNormalTable(): number[] {
  const table: number[] = [];
  for (let i = 0; i < INV_NORMAL_ENTRIES; i++) {
    table.push(Math.round(Q16 * quantile((i + 0.5) / INV_NORMAL_ENTRIES, 0, 1)));
  }
  return table;
}

// Row r: the share of a normal of mean r / 20 and SD 1.9 in each band of the 0-10 ladder, split into exactly 1,000,000 ppm.
function bandShareTable(): number[] {
  const scratch = createApportionScratch(reserveArena(SCRATCH_ARENA_BYTES), BAND_COUNT);
  const weights: number[] = [];
  const seats = new Float64Array(BAND_COUNT);
  const table: number[] = [];
  for (let row = 0; row < BAND_ROWS; row++) {
    const mean = row / BAND_MEANS_PER_POINT;
    let below = 0;
    for (let band = 0; band < BAND_CUTS.length; band++) {
      const upTo = cdf(BAND_CUTS[band], mean, BAND_SD);
      weights[band] = Math.round((upTo - below) * TWO_POW_32);
      below = upTo;
    }
    weights[BAND_CUTS.length] = Math.round((1 - below) * TWO_POW_32);
    apportion(PPM, weights, BAND_COUNT, seats, scratch);
    table.push(...seats);
  }
  return table;
}

// A Gaussian copula with correlation r has Spearman (6 / pi) * asin(r / 2), so r = 2 sin(pi * spearman / 6).
function copulaTable(): number[] {
  const r = 2 * sin((Math.PI * COPULA_SPEARMAN) / 6);
  const s = Math.sqrt(1 - r * r);
  const table: number[] = [];
  for (let income = 0; income < COPULA_SIDE; income++) {
    for (let noise = 0; noise < COPULA_SIDE; noise++) {
      const z = r * quantile((income + 0.5) / COPULA_SIDE, 0, 1) + s * quantile((noise + 0.5) / COPULA_SIDE, 0, 1);
      table.push(Math.round(MAX_UINT16 * cdf(z, 0, 1)));
    }
  }
  return table;
}

// The walking step's sine over a quarter of the 256 headings, from 0 to 1,024 Q8. walk.ts mirrors it into both
// parts of every heading's step at load, so the worker ships 65 numbers instead of 512.
function walkSineTable(): number[] {
  const table: number[] = [];
  for (let k = 0; k <= QUARTER_TURN; k++) table.push(Math.round(WALK_Q8_PER_TICK * sin((2 * Math.PI * k) / HEADINGS)));
  return table;
}

// Entry i is K * exp(sigma * z_i), where z_i is the normal quantile at (i + 0.5) / 256 and K sets the last entry to
// 4,095, the largest 12-bit weight.
function lognormalWeights(sigma: number): number[] {
  const spread: number[] = [];
  for (let i = 0; i < WEIGHT_ENTRIES; i++) spread.push(exp(sigma * quantile((i + 0.5) / WEIGHT_ENTRIES, 0, 1)));
  const scale = MAX_WEIGHT / spread[WEIGHT_ENTRIES - 1];
  return spread.map((value) => Math.round(scale * value));
}

export function buildTables() {
  return {
    LOG2_Q16: log2Table(),
    FADE_0_35Y: fadeTable(0.35),
    FADE_1Y: fadeTable(1),
    FADE_2_6Y: fadeTable(2.6),
    INV_NORMAL_Q16: inverseNormalTable(),
    BAND_SHARE_PPM: bandShareTable(),
    COPULA_Q16: copulaTable(),
    WALK_SINE_Q8: walkSineTable(),
    EXP2_Q30: exp2Table(),
    // Sigma 0.07 matches the stationary cash Gini of 0.03-0.05 (measured here, M2.2 plan Ruling 7).
    CASH_WEIGHTS: lognormalWeights(0.07),
    // Sigma 0.025 matches the stationary price CV of 0.018-0.030 (measured here, M2.2 plan Ruling 7).
    PRICE_WEIGHTS: lognormalWeights(0.025),
    // Sigma 0.5 matches the stationary firm-size CV of 0.49-0.70 (measured here, M2.2 plan Ruling 7).
    FIRM_SIZE_WEIGHTS: lognormalWeights(0.5),
  };
}

type TableName = keyof ReturnType<typeof buildTables>;

const ARRAY_TYPE: Record<TableName, 'Uint16Array' | 'Int32Array' | 'Uint32Array'> = {
  LOG2_Q16: 'Uint16Array',
  FADE_0_35Y: 'Uint16Array',
  FADE_1Y: 'Uint16Array',
  FADE_2_6Y: 'Uint16Array',
  INV_NORMAL_Q16: 'Int32Array',
  BAND_SHARE_PPM: 'Int32Array',
  COPULA_Q16: 'Uint16Array',
  WALK_SINE_Q8: 'Uint16Array',
  EXP2_Q30: 'Uint32Array',
  CASH_WEIGHTS: 'Uint16Array',
  PRICE_WEIGHTS: 'Uint16Array',
  FIRM_SIZE_WEIGHTS: 'Uint16Array',
};

function declaration(name: TableName, values: number[]): string {
  const rows: string[] = [];
  for (let first = 0; first < values.length; first += VALUES_PER_ROW) {
    rows.push(`  ${values.slice(first, first + VALUES_PER_ROW).join(', ')},`);
  }
  return `export const ${name} = /* @__PURE__ */ new ${ARRAY_TYPE[name]}([\n${rows.join('\n')}\n]);`;
}

function moduleSource(): string {
  const tables = Object.entries(buildTables()) as [TableName, number[]][];
  return `${HEADER}\n${tables.map(([name, values]) => declaration(name, values)).join('\n')}\n`;
}

if (import.meta.main) {
  writeFileSync(new URL('../src/maths/tables.ts', import.meta.url), moduleSource());
}
