"""Rebuild docs/plan/tasks/README.md, the roadmap, from the milestone folders: python tools/plan/roadmap.py

The roadmap is generated, never edited by hand. It copies each milestone.md's sub-milestone table and
total, the plan's ongoing items, and every task's "Owner decision first" lines, and shows which tasks
have a step-by-step plan or only an implementation brief, so it cannot drift from them.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PLAN = ROOT / 'docs' / 'plan' / 'implementation-plan.md'
TASKS = ROOT / 'docs' / 'plan' / 'tasks'
OUT = TASKS / 'README.md'
LAST_BEFORE_LAUNCH = 8                 # the owner moved launch after M8 on 6 October 2026


def days(text):
    lo, hi = re.search(r'([\d.]+)(?:–([\d.]+))?', text).groups()
    return float(lo), float(hi or lo)


def fmt(x):
    return f'{x:g}'


def cell(text):
    return text.replace('|', '\\|')


def plain(text):
    return re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', text)


def ongoing(plan):
    block = re.search(r'^\*\*Ongoing\*\*\n(.*?)^\*\*', plan, re.S | re.M).group(1)
    items = [line[6:] for line in block.splitlines() if line.startswith('- [ ] ')]
    rows = [r for r in plan.splitlines() if r.startswith('| ') and r.rstrip().endswith('| Ongoing |')]
    items += [f'{r.split("|")[1].strip()} ({r.split("|")[2].strip().lower()}; verify-first table)' for r in rows]
    return items


def decisions(task):
    out, lines = [], task.read_text(encoding='utf-8').splitlines()
    for i, line in enumerate(lines):
        if '**Owner decision first:**' in line:
            rest = line.split('**Owner decision first:**', 1)[1].strip()
            items, j = ([rest] if rest else []), i + 1
            while not rest and j < len(lines) and lines[j].startswith('  -'):
                items.append(lines[j].strip()[2:])
                j += 1
            out += [item.rstrip(';.').replace('](../../../', '](../') for item in items]
    return out


def how(task_dir):
    plan = task_dir / 'plan.md'
    if not plan.exists():
        return '—'
    kind = 'step plan' if '## Global Constraints' in plan.read_text(encoding='utf-8') else 'brief'
    return f'[{kind}]({task_dir.parent.name}/{task_dir.name}/plan.md)'


def milestone(folder):
    text = (folder / 'milestone.md').read_text(encoding='utf-8')
    title = re.match(r'# (M\d+ [^:]+):', text).group(1)
    tasks = {d.name.split('-', 1)[0]: d for d in folder.iterdir() if d.is_dir()}
    rows = []
    for line in text.splitlines():
        if re.match(r'\| \[?M\d+\.\d+ ', line):
            name, delivers, estimate = [c.strip() for c in line.strip().strip('|').split('|')][:3]
            key = plain(name).split(' ', 1)[0].lower()
            rows.append((plain(name), delivers, estimate, tasks.get(key)))
    total = re.search(r'\| \*\*Total\*\* \|[^|]*\| \*\*([^*]+)\*\*', text).group(1)
    owner = [(plain(n).split(' ', 1)[0], d) for n, _, _, t in rows if t for d in decisions(t / 'task.md')]
    return title, folder.name, rows, total, owner


def main():
    plan = PLAN.read_text(encoding='utf-8')
    folders = sorted((p for p in TASKS.iterdir() if p.is_dir() and re.match(r'm\d-[a-z]', p.name)),
                     key=lambda p: int(p.name[1]))
    milestones = [milestone(f) for f in folders]
    out = ['# Roadmap: milestones and sub-milestones', '',
           'Every milestone of the [implementation plan](../implementation-plan.md) has a folder here. Its `milestone.md` gives the overview and the progress table, and each sub-milestone has its own folder with `task.md` (what to build and the checks that close it) and `plan.md` (how to build it: a step-by-step plan, or a brief that becomes one just before the work starts). [Checkpoints](../checkpoints/README.md) record where the work stands. This page is generated by `python tools/plan/roadmap.py`; edit the milestone folders, not this page.', '',
           'Estimates are full-time days for one person coding by hand (unsourced estimates). They size the work: Claude Code plans and builds Nomos, and M0.1\'s Actual time sets the factor that rescales everything after it. Launch comes after M8, as the owner decided on 6 October 2026, and M9 follows launch.', '',
           '| Milestone | Sub-milestones | Estimate |', '| --- | --- | --- |']
    before, after = [0.0, 0.0], [0.0, 0.0]
    for title, name, rows, total, _ in milestones:
        n = int(title[1:].split(' ')[0])
        lo, hi = days(total)
        bucket = before if n <= LAST_BEFORE_LAUNCH else after
        bucket[0] += lo
        bucket[1] += hi
        out.append(f'| [{title}]({name}/milestone.md) | {len(rows)} | {total} |')
        if n == LAST_BEFORE_LAUNCH:
            out.append(f'| **Before launch, M0–M{n}** | | **{fmt(before[0])}–{fmt(before[1])} days** |')
    out.append(f'| **Everything** | | **{fmt(before[0] + after[0])}–{fmt(before[1] + after[1])} days** |')
    out += ['', 'The plan\'s own effort lines sum to about 210–322 days before launch, but many tasks that rounds 2, 6, 8 and 9 added carry no estimate there. These breakdowns estimate every task, which is why their sum is larger.', '',
            '## Sub-milestones in build order', '']
    for title, name, rows, _, _ in milestones:
        out += [f'### [{title}]({name}/milestone.md)', '', '| Sub-milestone | Delivers | Estimate | How |', '| --- | --- | --- | --- |']
        for label, delivers, estimate, task in rows:
            link = f'[{label}]({name}/{task.name}/task.md)' if task else label
            out.append(f'| {link} | {cell(delivers)} | {estimate} | {how(task) if task else "—"} |')
        out.append('')
    out += ['## Ongoing', '', 'These belong to no milestone and run until launch or beyond.', '']
    out += [f'- {item}' for item in ongoing(plan)]
    out += ['', 'M6.4, M6.5, M8.6 and M8.7 close on the two round 9 edit tests above, since the plan gives those editors no exit checks of their own.', '',
            '## Owner decisions, in build order', '',
            'Each must be settled before its sub-milestone starts. The task files give the context.', '',
            '| Before | Decision |', '| --- | --- |']
    out += [f'| {where} | {cell(what)} |' for m in milestones for where, what in m[4]]
    OUT.write_text('\n'.join(out) + '\n', encoding='utf-8')
    count = sum(len(m[4]) for m in milestones)
    print(f'{len(milestones)} milestones; before launch {fmt(before[0])}–{fmt(before[1])} days; {count} owner decisions')


if __name__ == '__main__':
    main()
