"""Rebuild docs/plan/tasks/2026-10-07-roadmap.md from the milestone breakdowns: python tools/plan/roadmap.py

The roadmap is generated, never edited by hand: it copies each breakdown's sub-milestone table and
total, the plan's ongoing items, and every "Owner decision first" line, so it cannot drift from them.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PLAN = ROOT / 'docs' / 'plan' / 'implementation-plan.md'
TASKS = ROOT / 'docs' / 'plan' / 'tasks'
OUT = TASKS / '2026-10-07-roadmap.md'
LAST_BEFORE_LAUNCH = 8                 # the owner moved launch after M8 on 6 October 2026


def days(text):
    lo, hi = re.search(r'([\d.]+)(?:–([\d.]+))?', text).groups()
    return float(lo), float(hi or lo)


def fmt(x):
    return f'{x:g}'


def cell(text):
    return text.replace('|', '\\|')


def ongoing(plan):
    block = re.search(r'^\*\*Ongoing\*\*\n(.*?)^\*\*', plan, re.S | re.M).group(1)
    items = [line[6:] for line in block.splitlines() if line.startswith('- [ ] ')]
    rows = [r for r in plan.splitlines() if r.startswith('| ') and r.rstrip().endswith('| Ongoing |')]
    items += [f'{r.split("|")[1].strip()} ({r.split("|")[2].strip().lower()}; verify-first table)' for r in rows]
    return items


def milestone(path):
    text = path.read_text(encoding='utf-8')
    title = re.match(r'# (M\d+ [^:]+):', text).group(1)
    rows = [[c.strip() for c in line.strip().strip('|').split('|')]
            for line in text.splitlines() if re.match(r'\| M\d+\.\d+ ', line)]
    total = re.search(r'\| \*\*Total\*\* \|[^|]*\| \*\*([^*]+)\*\*', text).group(1)
    decisions, heading, lines = [], None, text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith('## M'):
            heading = line[3:].split(' ', 1)[0]
        if '**Owner decision first:**' in line:
            rest = line.split('**Owner decision first:**', 1)[1].strip()
            items, j = ([rest] if rest else []), i + 1
            while not rest and j < len(lines) and lines[j].startswith('  -'):
                items.append(lines[j].strip()[2:])
                j += 1
            decisions += [(heading, item.rstrip(';.')) for item in items]
    return title, path.name, rows, total, decisions


def main():
    plan = PLAN.read_text(encoding='utf-8')
    files = sorted((p for p in TASKS.glob('*.md') if re.search(r'-m\d-[a-z]', p.name)),
                   key=lambda p: int(re.search(r'-m(\d)-', p.name).group(1)))
    milestones = [milestone(p) for p in files]
    out = ['# Roadmap: milestones and sub-milestones', '',
           'Every milestone of the [implementation plan](../implementation-plan.md) is split into sub-milestones, each ending with software that runs and passes its own checks. This page lists them in build order; each milestone file holds the details, the dependencies and the progress columns. [Checkpoints](../checkpoints/README.md) record where the work stands. This page is generated by `python tools/plan/roadmap.py`; edit the milestone files, not this one.', '',
           'Estimates are full-time days for one person coding by hand (unsourced estimates). They size the work: Claude Code plans and builds Nomos, and M0.1\'s Actual time sets the factor that rescales everything after it. Launch comes after M8, as the owner decided on 6 October 2026, and M9 follows launch.', '',
           '| Milestone | Sub-milestones | Estimate | File |', '| --- | --- | --- | --- |']
    before, after = [0.0, 0.0], [0.0, 0.0]
    for title, name, rows, total, _ in milestones:
        n = int(title[1:].split(' ')[0])
        lo, hi = days(total)
        bucket = before if n <= LAST_BEFORE_LAUNCH else after
        bucket[0] += lo
        bucket[1] += hi
        out.append(f'| {title} | {len(rows)} | {total} | [{name[11:-3]}]({name}) |')
        if n == LAST_BEFORE_LAUNCH:
            out.append(f'| **Before launch, M0–M{n}** | | **{fmt(before[0])}–{fmt(before[1])} days** | |')
    out.append(f'| **Everything** | | **{fmt(before[0] + after[0])}–{fmt(before[1] + after[1])} days** | |')
    out += ['', 'The plan\'s own effort lines sum to about 210–322 days before launch, but many tasks that rounds 2, 6, 8 and 9 added carry no estimate there. These breakdowns estimate every task, which is why their sum is larger.', '',
            '## Sub-milestones in build order', '']
    for title, name, rows, _, _ in milestones:
        out += [f'### [{title}]({name})', '', '| Sub-milestone | Delivers | Estimate |', '| --- | --- | --- |']
        out += [f'| {r[0]} | {cell(r[1])} | {r[2]} |' for r in rows]
        out.append('')
    out += ['## Ongoing', '', 'These belong to no milestone and run until launch or beyond.', '']
    out += [f'- {item}' for item in ongoing(plan)]
    out += ['', 'M6.4, M6.5, M8.6 and M8.7 close on the two round 9 edit tests above, since the plan gives those editors no exit checks of their own.', '',
            '## Owner decisions, in build order', '',
            'Each must be settled before its sub-milestone starts. The milestone files give the context.', '',
            '| Before | Decision |', '| --- | --- |']
    out += [f'| {where} | {cell(what)} |' for m in milestones for where, what in m[4]]
    OUT.write_text('\n'.join(out) + '\n', encoding='utf-8')
    decisions = sum(len(m[4]) for m in milestones)
    print(f'{len(milestones)} milestones; before launch {fmt(before[0])}–{fmt(before[1])} days; {decisions} owner decisions')


if __name__ == '__main__':
    main()
