// Builds the person-name table: words drawn from the shared sound set, kept when they pass the filter, and written into
// sim-culture as a sorted module with Fantasy Map Generator's licence beside it. Run it to write both files, or with
// --check to name any that are stale. It prints what each rule rejected, then sample names for the owner to read.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { draw1 } from '@nomos/sim-core/kernels';
import { rejectName } from '../src/filters/name-filter.ts';
import { FIXTURES } from '../src/filters/real-world.ts';
import { drawWord, loadSoundSet, type SoundSet } from '../src/sound-set/sound-set.ts';

export const PERSON_SEED = 1;
export const TABLE_WORDS = 1_024;
const MIN_LETTERS = 4;
const MAX_LETTERS = 10;
const WORDS_PER_LINE = 8;
const SAMPLE_NAMES = 40;
// Any stream shows how names read, so this one only has to stay fixed.
const SAMPLE_STREAM = 2;
const ROOT = new URL('../../../', import.meta.url);
const NAMING = 'packages/sim-culture/src/naming/';
const HEADER =
  "// Generated by tools/names/scripts/words.ts from Fantasy Map Generator's name bases, by Azgaar with Dopu and\n" +
  '// Avengium (MIT, LICENSE-fmg.txt beside this file). Do not edit.\n';
// The order a candidate is tried in; its first broken rule is the one counted. rejectName tries its own six in order.
const RULES = ['length', 'repeat', 'source', 'franchise', 'real-world', 'place', 'species', 'profanity', 'denied'];

export interface Table {
  readonly words: string[];
  readonly drawn: number;
  readonly rejected: Record<string, number>;
  readonly byLength: Record<number, [drawn: number, kept: number]>;
}

function firstBrokenRule(word: string, sounds: SoundSet, kept: ReadonlySet<string>): string | null {
  if (word.length < MIN_LETTERS || word.length > MAX_LETTERS) return 'length';
  if (kept.has(word)) return 'repeat';
  if (sounds.sources.has(word)) return 'source';
  return rejectName(word);
}

export function buildTable(seed: number): Table {
  const sounds = loadSoundSet();
  const kept = new Set<string>();
  const rejected: Record<string, number> = Object.fromEntries(RULES.map((rule) => [rule, 0]));
  const byLength: Record<number, [number, number]> = {};
  let drawn = 0;
  while (kept.size < TABLE_WORDS) {
    const word = drawWord(sounds, seed, drawn);
    drawn++;
    const rule = firstBrokenRule(word, sounds, kept);
    const counts = (byLength[word.length] ??= [0, 0]);
    counts[0]++;
    if (rule === null) {
      kept.add(word);
      counts[1]++;
    } else {
      rejected[rule] = (rejected[rule] ?? 0) + 1;
    }
  }
  return { words: [...kept], drawn, rejected, byLength };
}

export function tableSource(words: readonly string[]): string {
  const sorted = [...words].sort();
  const rows: string[] = [];
  for (let first = 0; first < sorted.length; first += WORDS_PER_LINE) {
    const quoted = sorted.slice(first, first + WORDS_PER_LINE).map((word) => `'${word}'`);
    rows.push(`  ${quoted.join(', ')},`);
  }
  return `${HEADER}export const NAME_WORDS: readonly string[] = [\n${rows.join('\n')}\n];\n`;
}

function capitalised(word: string): string {
  return `${word[0].toUpperCase()}${word.slice(1)}`;
}

// interfaces.md's personName rule, applied to the table just built, since the module it reads may not exist yet.
function fullName(table: readonly string[], nameKey: number): string {
  const given = (nameKey & 0xffff) % table.length;
  let family = (nameKey >>> 16) % table.length;
  if (family === given) family = (family + 1) % table.length;
  return `${capitalised(table[given])} ${capitalised(table[family])}`;
}

function sampleNames(words: readonly string[]): string[] {
  const table = [...words].sort();
  const names: string[] = [];
  for (let i = 0; i < SAMPLE_NAMES; i++) names.push(fullName(table, draw1(PERSON_SEED, SAMPLE_STREAM, i)));
  return names;
}

function report(table: Table): string[] {
  const lines = [`drawn ${table.drawn}, kept ${table.words.length}`, 'rejected by rule:'];
  for (const [rule, count] of Object.entries(table.rejected)) lines.push(`  ${rule}: ${count}`);
  lines.push('by length:');
  for (const [length, [drawn, kept]] of Object.entries(table.byLength)) {
    lines.push(`  ${length} letters: ${drawn} drawn, ${kept} kept`);
  }
  lines.push(`${SAMPLE_NAMES} sample names:`);
  for (const name of sampleNames(table.words)) lines.push(`  ${name}`);
  return lines;
}

function outputs(words: readonly string[]): [path: string, text: string][] {
  return [
    [`${NAMING}words.ts`, tableSource(words)],
    [`${NAMING}LICENSE-fmg.txt`, readFileSync(new URL('LICENSE-fmg.txt', FIXTURES), 'utf8')],
  ];
}

// Git on Windows checks text out with CRLF, which must not make a file look stale.
function lf(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

function isStale(path: string, text: string): boolean {
  const file = new URL(path, ROOT);
  return !existsSync(file) || lf(readFileSync(file, 'utf8')) !== lf(text);
}

if (import.meta.main) {
  const table = buildTable(PERSON_SEED);
  const files = outputs(table.words);
  if (process.argv.includes('--check')) {
    const stale = files.filter(([path, text]) => isStale(path, text)).map(([path]) => path);
    if (stale.length > 0) {
      console.error(`stale, rebuild with node tools/names/scripts/words.ts:\n  ${stale.join('\n  ')}`);
      process.exitCode = 1;
    } else {
      console.log(`${files.length} generated files are up to date`);
    }
  } else {
    mkdirSync(new URL(NAMING, ROOT), { recursive: true });
    for (const [path, text] of files) writeFileSync(new URL(path, ROOT), text);
    console.log(report(table).join('\n'));
  }
}
